---
stages:
  - name: validate
    deps:
    resources:
      - name: noope
        uri: /function/piedpiper-noop-gateway
    config:
      - resource: noop
  - name: style
    deps:
      - validate
    resources:
      - name: noop
        uri: /function/piedpiper-noop-gateway
    config:
      - files: "*.py"
        resource: noop
  - name: sast
    deps:
      - validate
    resources:
      - name: noop
        uri: /function/piedpiper-noop-gateway
    config:
      - files: "*"
        resource: noop
  - name: unit
    deps:
    resources:
      - name: noop
        uri: /function/piedpiper-noop-gateway
    config:
      - resource: noop
        tox_arguments: -e unit
  - name: build
    deps:
    resources:
      - name: noop
        uri: /function/piedpiper-noop-gateway
    config:
      - target: "Dockerfile"
        resource: noop
  - name: package
    deps:
      - build
    resources:
      - name: noop
        uri: /function/piedpiper-noop-gateway
    config:
      - files: "*"
        resource: noop

